version: '3.1'

services:

  db:
    container_name: vehicle
    image: gufalcon/vehicle:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - postgres

networks:
  postgres:
    driver: bridge