##############################################
### Greeting
##############################################
GET http://localhost:8080/api/q/health

##############################################
### Greeting
##############################################
GET http://localhost:8080/api/hello

##############################################
### Vehicle Old
##############################################
GET http://localhost:8080/api/vehicles
###

GET http://localhost:8080/api/vehicles/23
###

GET http://localhost:8080/api/vehicles/search?id=23

##############################################
### Vehicle Panache
##############################################

GET http://localhost:8080/api/vehicles/count

###

GET http://localhost:8080/api/vehicles
###

##############################################
### Customer Panache
##############################################

GET http://localhost:8080/api/customers/count

###

GET http://localhost:8080/api/customers
###

##############################################
### Rental Panache
##############################################

GET http://localhost:8080/api/rentals/count

###

GET http://localhost:4200/api/rentals
###